language: node_js

before_install:

  # Install AWS CLI
  - pip install --user awscli

  # Install Pulumi
  - curl -fsSL https://get.pulumi.com | sh
  - export PATH="/home/travis/.pulumi/bin:/home/travis/bin:$PATH"
  - pulumi version
  - pulumi login

  # Install Hugo
  - wget https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb

before_script:
  - export TZ="America/Los_Angeles"

script:
  - make travis
