language: node_js

before_install:

  # Install AWS CLI
  - pip install --user awscli

  # Install Pulumi
  - curl -fsSL https://get.pulumi.com | sh
  - export PATH="/home/travis/.pulumi/bin:/home/travis/bin:$PATH"
  - pulumi version
  - pulumi login

  # Install Hugo
  - wget https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb

script:
  - make build
  - ./scripts/travis_${TRAVIS_EVENT_TYPE}.sh
  - aws cloudfront create-invalidation --distribution-id $(shell pulumi stack output cloudfrontDistributionId) --paths $(shell find site/public -name "*.html" -o -name "*.css" -o -name "*.js" | sed "s/^site\/public//g")
