/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface CdnRating {
    'rating': number;
  }
  interface CdnRatingAttributes extends StencilHTMLAttributes {
    'rating'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'CdnRating': Components.CdnRating;
  }

  interface StencilIntrinsicElements {
    'cdn-rating': Components.CdnRatingAttributes;
  }


  interface HTMLCdnRatingElement extends Components.CdnRating, HTMLStencilElement {}
  var HTMLCdnRatingElement: {
    prototype: HTMLCdnRatingElement;
    new (): HTMLCdnRatingElement;
  };

  interface HTMLElementTagNameMap {
    'cdn-rating': HTMLCdnRatingElement
  }

  interface ElementTagNameMap {
    'cdn-rating': HTMLCdnRatingElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
