languageCode = "en-us"
title = "Christian Nunciato"
sectionPagesMenu = "main"

[params]
mediaRoot = "https://s3.amazonaws.com/cnunciato-website-media/"

[mediaTypes."application/rss"]
suffixes = ["xml"]

[outputFormats.RSS]
mediaType = "application/rss"
baseName = "index"
isPlainText = false
